### ISSUE TITLE
Annual report detail screen: Cost Type Filter Not Working

### ISSUE THREAD

**Issue by hoannbhe160107** [tuannqhe151337/fin-planning-frontend#129]
---
name | reason | how to fix | assignees
--- | --- | --- | --- |
:bug: Cost Type Filter Not Working | Cost type filter is not displaying any options | Implement proper fetching and rendering of cost types in the filter | hoannbhe160107 |
---

## :bug: Bug Report

**Current Behavior**
The cost type filter is not displaying any options in the dropdown list. As a result, users are unable to filter costs by type

**Steps to reproduce**
- Step 1: Navigate to the annual reprt detail page 
- Step 2: Select Detail tab on tablist
- Step 3: Select the cost type filter dropdown
**Input Code**

**Expected behavior/code**
The cost type filter should display a list of available cost types for selection, allowing users to filter the costs accordingly

**Environment**
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
![Screenshot 2024-08-01 161337](https://github.com/user-attachments/assets/a4531f99-6770-49e5-9055-c6372595983a)

**Comment by tunmhe150840** [comment]
Result after merged [feature/annual-report-reports-fix-bug](https://github.com/tuannqhe151337/fin-planning-backend/tree/feature/annual-report-reports-fix-bug)
![image](https://github.com/user-attachments/assets/08d11d39-2cc9-4aa8-b698-b42ef07a8bfe)
![image](https://github.com/user-attachments/assets/640e8841-cefb-46c7-bd12-97ce3e9a2969)
