### ISSUE TITLE
Annual report detail screen: Department Filter Not Working 

### ISSUE THREAD

**Issue by hoannbhe160107** [tuannqhe151337/fin-planning-frontend#130]
---
name | reason | how to fix | assignees
--- | --- | --- | --- |
:bug: Department Filter Not Working | Department filter is not displaying any options | Implement proper fetching and rendering of department in the filter | hoannbhe160107 |
---

## :bug: Bug Report

**Current Behavior**
The department filter is not displaying any options in the dropdown list. As a result, users are unable to filter department

**Steps to reproduce**
- Step 1: Navigate to the annual reprt detail page 
- Step 2: Select Detail tab on tablist
- Step 3: Select the department filter dropdown
**Input Code**

**Expected behavior/code**
The department filter should display a list of available department for selection, allowing users to filter the departments accordingly

**Environment**
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**
![Screenshot 2024-08-01 161653](https://github.com/user-attachments/assets/a23bafbf-0fa7-4efc-b5c2-d0a8441e0612)

**Comment by tunmhe150840** [comment]
Result after merged [fix-authority-for-feature](https://github.com/tuannqhe151337/fin-planning-backend/tree/fix-authority-for-feature):
 
![image](https://github.com/user-attachments/assets/1c09567e-9165-46fb-a074-9954f39a224a)
![image](https://github.com/user-attachments/assets/05afa97e-fe00-4bfd-8c57-592107e13020)
