### ISSUE TITLE
Report detail expense screen: Status Filter Incorrect Options

### ISSUE THREAD

**Issue by hoannbhe160107** [tuannqhe151337/fin-planning-frontend#132]
---
name | reason | how to fix | assignees
--- | --- | --- | --- |
:bug: Status Filter Incorrect Options | Status filter displaying incorrect status options | Implement correct fetching and mapping of status options | hoannbhe160107 |
---

## :bug: Bug Report

**Current Behavior**
The status filter is displaying incorrect status options, which are not relevant to the current context or application state

**Steps to reproduce**

**Input Code**

**Expected behavior/code**
The status filter should display the correct status options that are relevant to the application context, allowing users to filter items by appropriate statuses

**Environment**
- OS: Windows 10

**Possible Solution**
Ensure that the status options are properly fetched from the backend and correctly mapped to the dropdown list. Verify the API endpoint and check if the correct status data is being received and displayed

**Additional context/Screenshots**
![ád](https://github.com/user-attachments/assets/4c44bac0-80f3-40ad-a75a-7b27a2e0644f)

**Comment by tunmhe150840** [comment]
New api to get correct status of expense
![image](https://github.com/user-attachments/assets/cae9a0ad-88e4-416a-9965-52f997278475)
