### ISSUE TITLE
Update user screen: Date of Birth Displayed Incorrectly

### ISSUE THREAD

**Issue by hoannbhe160107** [tuannqhe151337/fin-planning-frontend#177]
---
name | reason | how to fix | assignees
--- | --- | --- | --- |
:bug: Date of Birth Displayed Incorrectly | Date of birth is being displayed incorrectly on the update user page | Correct the date format and ensure proper timezone handling | hoannbhe160107 |
---

## :bug: Bug Report

**Current Behavior**
The date of birth field is displaying the incorrect date on the update user page. The date shown is not the same as the date that was initially entered or expected.

**Steps to reproduce**
Step 1: Navigate to the update user page
Step 2: Observe the date of birth displayed in the update user page

**Input Code**
N/A

**Expected behavior/code**
![image](https://github.com/user-attachments/assets/08c03944-4d57-447e-9ba3-0f935d402d52)

**Environment**
- OS: Windows 10

**Possible Solution**
Check the date format handling and ensure that the date is properly stored and retrieved from the database. Also, verify that there is no issue with timezone conversion that could be affecting the displayed date

**Additional context/Screenshots**

**Comment by tuannqhe151337** [comment]
Holy shit I couldn't belive i could have done it!

![abosidufhaosiudfhaosd](https://github.com/user-attachments/assets/9c0c9e8c-9499-4e41-a529-34a90de836a8)
