### ISSUE TITLE
Home screen with accoutant role: Information Not Displaying in Dark Mode on Table

### ISSUE THREAD

**Issue by hoannbhe160107** [tuannqhe151337/fin-planning-frontend#197]
---
name | reason | how to fix | assignees
--- | --- | --- | --- |
:bug: Information Not Displaying in Dark Mode on Table | information not visible when hovering over the annual report table in dark mode | correct visibility and styling in dark mod | hoannbhe160107 |
---

## :bug: Bug Report

**Current Behavior**
When hovering over the annual report table on the home screen with the Accountant role in dark mode, no information is displayed

**Steps to reproduce**
Step 1: Login with accoutant role
Step 2: Access to Home page

![image](https://github.com/user-attachments/assets/ce0810d9-e67c-487d-9d9a-c782036ef6b1)

**Input Code**
N/A

**Expected behavior/code**

**Environment**
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**

**Comment by tuannqhe151337** [comment]
Holy shit I couldn't believe I could have done it!

![abosidufhaosiudfhaosd](https://github.com/user-attachments/assets/f46d7e36-789a-49e6-a107-e648a47ab0ca)
