### ISSUE TITLE
Home screen should display chart, report for previous year

### ISSUE THREAD

**Issue by baonnhe161928** [tuannqhe151337/fin-planning-frontend#201]
---
name | assignees
---  | --- |
:bug: Home screen should display chart, report for previous year | tuannqhe151337 |
---

## :bug: Bug Report

**Current Behavior**
Home screen should display chart, report for previous year

**Steps to reproduce**
Step 1: Login with accoutant role
Step 2: Access to Home page

![image](https://github.com/user-attachments/assets/1f1b103d-782c-4388-bc0c-675247f9a929)

**Input Code**
N/A

**Expected behavior/code**

**Environment**
- OS: Windows 10

**Possible Solution**

**Additional context/Screenshots**

**Comment by tuannqhe151337** [comment]
Change to current year: Backend already fix!
